### ISSUE TITLE
Cannot build on MC1.12.2

### ISSUE THREAD

**Issue by Albonation** [Albonation/OpenComputers#1]
-cannot find symbol class StatCollector
-cannot find symbol class ForgeDirection
-package cpw.mods.fml.common does not exist
-package cpw.mods.fml.relauncher does not exist
-cannot find symbol class EnumChatFormatting
-cannot find symbol class Vec3
-cannot find symbol class S35PacketUpdateTileEntity
-cannot find symbol class API
-"                                   " llcon
-"                                   " MovingObjectPosition

**Comment by Albonation** [comment]
the issues are isolated to a dependency on Thaumcraft. Perhaps the API for Thaumcraft. My plan is to remove all integration with Thaumcraft and get rid of this dependency.
